export const permissions = [
  "dashboard.view",
  "nodes.view",
  "nodes.create",
  "nodes.update",
  "nodes.rotateTokens",
  "nodes.maintenance",
  "nodes.config.view",
  "nodes.config.generate",
  "nodes.updateControl",
  "servers.view",
  "servers.create",
  "servers.update",
  "servers.delete",
  "servers.power",
  "servers.network.view",
  "servers.network.update",
  "servers.network.manage",
  "servers.settings.view",
  "servers.settings.update",
  "servers.console.view",
  "servers.console.command",
  "servers.files.view",
  "servers.files.write",
  "servers.files.delete",
  "servers.files.upload",
  "servers.files.download",
  "servers.files.archive",
  "servers.environment.view",
  "servers.environment.write",
  "servers.backups.view",
  "servers.backups.create",
  "servers.backups.restore",
  "servers.backups.delete",
  "servers.schedules.view",
  "servers.schedules.create",
  "servers.schedules.run",
  "servers.metrics.view",
  "servers.subusers.view",
  "servers.subusers.update",
  "servers.members.view",
  "servers.members.manage",
  "templates.view",
  "templates.create",
  "templates.update",
  "allocations.view",
  "allocations.update",
  "backups.view",
  "backups.create",
  "backups.restore",
  "backupTargets.view",
  "backupTargets.update",
  "tasks.view",
  "tasks.create",
  "tasks.run",
  "users.view",
  "users.update",
  "roles.view",
  "roles.update",
  "roles.create",
  "webhooks.view",
  "webhooks.update",
  "alerts.view",
  "alerts.update",
  "audit.view",
  "settings.view",
  "settings.update",
  "apiKeys.view",
  "apiKeys.create",
  "apiKeys.revoke",
  "integrations.view",
  "integrations.update",
] as const;

export type Permission = (typeof permissions)[number];

export const hasPermission = (
  grantedPermissions: string[],
  required: Permission | Permission[],
): boolean => {
  if (grantedPermissions.includes("*")) {
    return true;
  }

  const requiredPermissions = Array.isArray(required) ? required : [required];
  return requiredPermissions.every((permission) =>
    grantedPermissions.includes(permission),
  );
};
